### PR TITLE
Add Recommendations placeholder index page

### LINKED ISSUE #10: Add Placeholder for Recommendation Index Page
Create the placeholder index page for Recommendation.

- [x] There is a JavaScript index page file for Recommendation.
- [x] Clicking the List Recommendations option in the nav bar links to the correct page.
- [x] Index page has placeholder header and connects to API

### PR DESCRIPTION
**Pull request by TokyoExpress**
Added the Recommendations placeholder index page, along with tests. Also reintegrates the team02 backend.

100% coverage, all mutations killed

Closes https://github.com/ucsb-cs156-s22/team03-s22-5pm-3/issues/10

### CODE REVIEW

**Review by aaron-sgy — CHANGES_REQUESTED** [review]
- The navbar button is not routing to the Recommendation Index Page
- you need to edit App.js to route the navbar button to the index page
- you need to edit the index page content.  (less important) but supposedly you need to change “This is Help Request Index Page” to “This is Recommendation Request Index Page”

**Comment by TokyoExpress** [comment]
fixed navbar and app routing

**Comment by TokyoExpress** [comment]
fixed app routing

**Review by jwangathan — APPROVED** [review]
LGTM. All tests passed.

**Comment by aaron-sgy** [comment]
LGTM. Ready to Merge. Checking Mutation Test locally.

**Comment by aaron-sgy** [comment]
100% Mutation Test.

**Review by aaron-sgy — APPROVED** [review]

**Pull request merged**
