### PR TITLE
Add Recommendation component to storybook and fixtures

### LINKED ISSUE #12: Add RecommendationTable component to Storybook (along with fixtures)
Implement the Recommendation Table part of the Storybook.

- [x] There is a folder under frontend/src/stories/components with the name Recommendation with a file inside it called RecommendationTable.stories.js
- [x] There is a file under the frontend/src/fixtures folder with the name RecommendationFixtures.js
- [x] There are two fixtures inside the RecommendationFixtures.js file: one with one Recommendation and another one with three Recommendations
- [x] When the fixtures are viewed on Storybook, they appear as expected (empty one should not have anything, the one with three Recommendations should have all fields set as expected).

### PR DESCRIPTION
**Pull request by TokyoExpress**
Added RecommendationTable to storybook. Added fixtures for Recommendation.

100% coverage, all mutations killed

Closes https://github.com/ucsb-cs156-s22/team03-s22-5pm-3/issues/12

### CODE REVIEW

**Comment by aaron-sgy** [comment]
No storybook or fixture added...Wrong match between PR and Task?

**Review by aaron-sgy — CHANGES_REQUESTED** [review]
No storybook or fixture added...Wrong match between PR and Task?

**Comment by TokyoExpress** [comment]
storybook and fixtures. something happened with the commit

**Comment by aaron-sgy** [comment]
Storybook and Fixtures Work. Routing Correct for Recommendation Index Page. 100% Test Coverage. Running Stryker Mutation Test locally.

**Review by aaron-sgy — APPROVED** [review]

**Pull request closed without merging**
