### PR TITLE
Implemented UCSBOrganization Table and Fixtures and added to storybook

### LINKED ISSUE #7: Add OrganizationTable component to Storybook (along with fixtures)
- [x] There is a folder under frontend/src/stories/components with the name Organization with a file inside it called Organization.stories.js
- [x] There is a file under the frontend/src/fixtures folder with the name organizationFixtures.js
- [x] There are two fixtures inside the organizationFixtures.js file: one with one Organization and another one with three Organizations
- [x] When the fixtures are viewed on Storybook, they appear as expected (empty one should not have anything, the one with three Organizations should have all fields set as expected)

### LINKED ISSUE #8: Replace OrganizationTable placeholder page with one that includes Organization Table
- [x] Replace Organization code with code from the Javascript index page
- [x] Check if the index page is correctly connected to the correct backend API
- [x] Check if the actual table shows up on the front end
- [x] There is full test coverage (Jacoco) for SomethingRequestController
- [x] There is full mutation test coverage (Pitest) for the newly added code

### PR DESCRIPTION
**Pull request by jwangathan**
Created UCSBOrganization Table and updated the Index page and its corresponding tests. Tested with 100% coverage using "npm run coverage". Added OrganizationTable to storybook and implemented fixtures. Closes #7 #8 .

### CODE REVIEW

**Review by aaron-sgy — APPROVED** [review]
LGTM

**Comment by aaron-sgy** [comment]
100% Stryker Mutation test locally

**Comment by TokyoExpress** [comment]
Tests pass for me. LGTM

**Review by TokyoExpress — APPROVED** [review]

**Comment by aaron-sgy** [comment]
running one last Stryker mutation test after changes.

**Comment by aaron-sgy** [comment]
100% Mutation Tests. Merging.

**Pull request merged**
